			<hr>

			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<!-- CalculONotes -->
			<ins class="adsbygoogle"
			     style="display:block"
			     data-ad-client="ca-pub-5957946549282152"
			     data-ad-slot="5604004341"
			     data-ad-format="auto"></ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>

			<hr>

			<footer class="text-center" style="color: #A0A0A0;">
				<div>© 2017 — <a href="http://gildev.tk">GilDev</a></div>
				<div>
					<a href="http://twitter.com/GilDev"><img src="images/twitter.png"></a>
					<a href="http://gildev.tk"><img src="images/gildev.png"></a>
					<a href="http://facebook.com/GilDev"><img src="images/facebook.png"></a>
				</div>
				Fait avec <a href="https://www.slimframework.com/">Slim Framework</a>
			</footer>
		</div>
	</body>
</html>